config/routes.rb
Rails.application.routes.draw do
  get 'team' => 'statics#team'
  get 'contact' => 'statics#contact'
  get 'welcome/:first_name' => 'statics#welcome'

  resources :gossips
 
  # set le root en redirigeant le / vers /gossips 
  root to: redirect('/gossips')
  
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :likesgossip, only: [:new, :create, :destroy]
  resources :cities

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(content: params[:content], user_id: current_user.id, gossip_id: params[:gossip_id], commentable: [Gossip.all, Comment.all].sample.sample)
    flash[:notice] = "Le commentaire a été publié ! "
    redirect_to gossip_path(params[:gossip_id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @path = Gossip.find_by(id: @comment.gossip_id)

    if @comment.update(content: params[:comment][:content])
      flash[:success] = "Le commentaire a été modifié."
      redirect_to @path
    else
      Rails.logger.info(@comment.errors.inspect) 
      render :edit
    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @path = Gossip.find_by(id: @comment.gossip_id)

    if @comment.destroy
      flash[:success] = "Le commentaire a été supprimé."
      redirect_to @path
    else
      Rails.logger.info(@comment.errors.inspect) 
      render :edit
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  
end

app/views/comments/edit.html.erb
<!DOCTYPE html>
<html>
    <center>
    <br>
      <h1><p class = "text-secondary">Modifier le commentaire</h1></p>
      <br>
          <%= form_for @comment, url: gossip_comment_url, method: :patch do |f| %>
          <br>

            <br>
            <div class = "form-group">
              <label>Votre commentaire :</label>
              <%= f.text_area :content, class: 'form-control', :value => @comment.content %>
            </div>

            <br>
            <div class = "form-group">
              <button type = "submit">Valider la modification</button>
            </div>

          <p></p>
        <% end %>
      <%= link_to "Revenir à la page d'accueil", root_path, :class=>"navbar-brand my_link" %>
      <br><br><br>
    </center>
  </body>
</html>