config/routes.rb
Rails.application.routes.draw do
  get 'team' => 'statics#team'
  get 'contact' => 'statics#contact'
  get 'welcome/:first_name' => 'statics#welcome'

  resources :gossips
 
  # set le root en redirigeant le / vers /gossips 
  root to: redirect('/gossips')
  
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :likesgossip, only: [:new, :create, :destroy]
  resources :cities

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable

  validates :title, presence: true #, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @colors = ["blue", "green", "brown", "purple", "orange"]
    @users = User.all
    @titles = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
  end

  def new
    @gossip = Gossip.new()
  end

  def create
    @gossip = Gossip.new(title: params['title'], content: params['content'], user_id: current_user.id)

    if @gossip.save
      flash[:success] = "Le potin a bien été créé !"
      redirect_to '/'
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find_by(id: params[:id])
  end

  def update
    @gossip = Gossip.find_by(id: params[:id])
    params_permitted = params.require(:gossip).permit(:title, :content)

    if @gossip.update(params_permitted)
      flash[:success] = "Le potin a été mis à jour !"
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find_by(id: params[:id])
    
    if (GossipTag.find_by(id: params[:id]) != nil)
      GossipTag.find_by(id: params[:id]).destroy
    end

    Comment.all.each { |c| 
    if c.gossip_id == params[:id]
       c.destroy
      end
    }

    @gossip.destroy
    flash[:success] = "Le potin a été détruit !"
    redirect_to '/'
  end

end

app/helpers/gossips_helper.rb
module GossipsHelper

  def already_exists?(gossip)
    return Like.where(user_id: current_user.id, gossip_id: gossip.id).length > 0
  end

end

app/views/gossips/edit.html.erb
<!DOCTYPE html>
<html>
    <center>
    <br>
      <h1><p class = "text-secondary">Modifier le potin</h1></p>
      <br>
          <%= form_for @gossip do |f| %>
          <br>

            <div class = "form-group">
              <label>Titre du potin :</label>
              <%= f.text_field :title, class: 'form-control' %>
            </div>

            <br>
            <div class = "form-group">
              <label>Contenu du potin :</label>
              <%= f.text_area :content, class: 'form-control' %>
            </div>

            <br>
            <div class = "form-group">
              <button type = "submit"> Valider la modification </button>
            </div>

          <p></p>
        <% end %>
    </center>
  </body>
</html>

app/views/gossips/index.html.erb
<!DOCTYPE html>
<html>
    <center>
    <br>
      <h1><p class = "text-secondary">The Gossip Project</p></h1>
      <p>
      <p><h4><p class = "text-secondary">Bienvenue sur la page des potins</p></h4>
      <br>
      <p><h6><p class = "text-secondary">La liste des potins :</p></h6>
      <br>

      <!-- POST-IT START -->
      <div class="container bootstrap snippets bootdeys">
        <div class="row">
          <% @titles.reverse_each.with_index do |gossip, index| %>
          <% inc = index % 5 %>
            <div class="col-4 content-card">
              <div class="card-big-shadow">
                <div class="card card-just-text" data-background="color" data-color="<%= @colors[inc] %>" data-radius="none">
                  <div class="content">
                    <h6 class="category">par <%= gossip.user.first_name %></h6>
                      <h4 class="title"><a href="/gossips/<%= gossip.id %>"><%= gossip.title %></a></h4>
                        <p class="description"><%= gossip.content %></p>
                          <i class="fas fa-thumbs-up">
                            <%counter_like = 0%>
                            <%Like.all.each do |like|%>
                              <% if (like.gossip_id == gossip.id) then counter_like+=1 end%>
                            <% end %>
                            <%=counter_like%>
                          </i>
                        <%if current_user%>
                        <%if already_exists?(gossip)%>
                          <br><br><%=button_to "J'aime pas", likesgossip_path(id: gossip.id), :class=>"btn btn-primary", method: :delete %>
                            <%else%>
                          <br><br><%=button_to "J'aime", likesgossip_index_path(gossip_id: gossip.id), :class=>"btn btn-primary", method: :post %>
                        <%end%>
                    <%end%>
                  </div>
                </div> <!-- end card -->
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <!-- POST-IT END -->
    </center>
  </body>
</html>

app/views/gossips/new.html.erb
<!DOCTYPE html>
<html>
    <center>
    <br>
      <h1><p class = "text-secondary">Créer un nouveau potin</h1></p>
      <br>
      <div class="card text-white bg-primary mb-3" style="width: 32rem;">
        <div class="card-body">
          <%= form_tag('/gossips', method: 'post') do %>
            <br>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= label_tag :title, "Nom du potin:" %><br>
            <%= text_field_tag :title, nil %><br><br>
            <%= label_tag :content, "Le contenu de votre potin:" %><br>
            <%= text_area_tag :content, nil, size: '60' %>
            <br><br>
            <%= submit_tag "Envoyer", data: { turbo: false } %>
            <br>
            <p></p>
          <% end %>
        </div>
      </div>
      <br><br>
      <% if @gossip.errors.any? %>
        <div class="alert alert-danger custom_alert" role="alert">
          <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
            <ul class="bullet">
              <li>Le titre doit avoir au minimum 3 caractères et maximum 14 caractères.</li>
              <li>Le content ne doit pas être vide.</li>
            </ul>
        </div>
      <% end %>
    </center>
  </body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
    <center>      
      <h1><p class = "text-secondary"><%= @gossip.title %></h1></p>
      <p>par <%= link_to "#{@user.first_name}", user_path(@user.id), :class=>"my_link" %></a> le <%= @gossip.created_at.strftime("%d/%m/%Y %H:%M") %></p>
      <p>Depuis la ville de <%= link_to "#{City.find(@user.city_id).name}", city_path(@user.city_id), :class=>"my_link" %></a></p> 
      <br>
      <p><%= @gossip.content %></p>
      <%if current_user && current_user.id == @user.id%>
        <br><%= button_to "Modifier ce potin", edit_gossip_path(@gossip.id), :class=>"btn btn-primary", method: :get %>
        <br>
        <%= button_to "Détruire ce potin", gossip_path(@gossip.id), :class=>"btn btn-primary", form: { data:{turbo_confirm: "Êtes-vous CERTAIN(E) ?"}}, method: :delete %>
      <%end%>
      <br><br>
      <br><h4><p class = "text-secondary">Espace commentaires</p></h4>

      <br>
        Il y a <%=@gossip.comments.count %> commentaires.
      <br>
      
      <% Comment.all.each do |c| %>
        <% if c.gossip_id == @gossip.id%>
          <br><%=User.find_by(id: c.user_id).first_name %> : <%= c.content%> - 
          <%if current_user && current_user.id == c.user_id %>
            <%=button_to "Editer", edit_gossip_comment_url(@gossip, c.id), :class=>"btn btn-warning", method: :get %>
            <%=button_to "Supprimer", gossip_comment_path(@gossip, c.id), :class=>"btn btn-danger", form: { data:{turbo_confirm: "Êtes-vous CERTAIN(E) ?"}}, method: :delete %>
          <%end%>
          <br>
        <% end %>
      <% end %>

      <i class="fas fa-thumbs-up">
        <%counter_like = 0%>
          <%Like.all.each do |like|%>
            <% if (like.gossip_id == @gossip.id) then counter_like+=1 end%>
          <% end %>
        <%=counter_like%>
      </i>

      <%if current_user%>
      <%if already_exists?(@gossip)%>
        <br><br><%=button_to "J'aime pas", likesgossip_path(id: @gossip.id), :class=>"btn btn-primary", method: :delete %>
          <%else%>
        <br><br><%=button_to "J'aime", likesgossip_index_path(gossip_id: @gossip.id), :class=>"btn btn-primary", method: :post %>
      <%end%>
        <br><br><h1><p class = "text-secondary">Rédiger un commentaire</h1></p><br>
        <%= form_tag(gossip_comments_path(@gossip), method: :post) do%>
          <%= label_tag "Rédiger un commentaire" %>
            <br><br>
              <%= text_area_tag :content, nil, placeholder: "Votre commentaire..", rows: 5, cols: 50 %>
            <br><br>
          <%= submit_tag "Publier ce commentaire.", data: {turbo:false} %>
        <% end %>
      <%end%>
    </center>
  </body>
</html>