config/routes.rb
Rails.application.routes.draw do
  get 'team' => 'statics#team'
  get 'contact' => 'statics#contact'
  get 'welcome/:first_name' => 'statics#welcome'

  resources :gossips
 
  # set le root en redirigeant le / vers /gossips 
  root to: redirect('/gossips')
  
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :likesgossip, only: [:new, :create, :destroy]
  resources :cities

  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  has_many :tags, through: :gossips
  
  validates :name, presence: true, length: { minimum: 2, maximum: 50 }
  validates :zip_code, presence: true, length: { is: 5 }, format: { with: /\A\d{5}\z/, message: 'Le code postal doit avoir un format 12345' }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable

  validates :title, presence: true #, length: { minimum: 3, maximum: 14 }
  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  validates :content, presence: true, length: { minimum: 5, maximum: 1000 }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
  
  validates :title, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :city
  has_many :gossips
  has_many :private_messages_sent, class_name: 'PrivateMessage', foreign_key: 'sender_id'
  has_many :private_messages_received, class_name: 'PrivateMessage', foreign_key: 'recipient_id'
  has_many :comments
  has_many :likes
  validates :password, presence: true, length: { minimum:6 }, confirmation: true
  validates :password_confirmation, presence: true
  validates :first_name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 }, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Format d'email invalide." }
  validates :age, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 13 }
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @colors = ["blue", "green", "brown", "purple", "orange"]
    @city = City.find_by(id: params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.create(content: params[:content], user_id: current_user.id, gossip_id: params[:gossip_id], commentable: [Gossip.all, Comment.all].sample.sample)
    flash[:notice] = "Le commentaire a été publié ! "
    redirect_to gossip_path(params[:gossip_id])
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    @path = Gossip.find_by(id: @comment.gossip_id)

    if @comment.update(content: params[:comment][:content])
      flash[:success] = "Le commentaire a été modifié."
      redirect_to @path
    else
      Rails.logger.info(@comment.errors.inspect) 
      render :edit
    end

  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @path = Gossip.find_by(id: @comment.gossip_id)

    if @comment.destroy
      flash[:success] = "Le commentaire a été supprimé."
      redirect_to @path
    else
      Rails.logger.info(@comment.errors.inspect) 
      render :edit
    end
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @colors = ["blue", "green", "brown", "purple", "orange"]
    @users = User.all
    @titles = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = User.find(@gossip.user_id)
  end

  def new
    @gossip = Gossip.new()
  end

  def create
    @gossip = Gossip.new(title: params['title'], content: params['content'], user_id: current_user.id)

    if @gossip.save
      flash[:success] = "Le potin a bien été créé !"
      redirect_to '/'
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find_by(id: params[:id])
  end

  def update
    @gossip = Gossip.find_by(id: params[:id])
    params_permitted = params.require(:gossip).permit(:title, :content)

    if @gossip.update(params_permitted)
      flash[:success] = "Le potin a été mis à jour !"
      redirect_to '/'
    else
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find_by(id: params[:id])
    
    if (GossipTag.find_by(id: params[:id]) != nil)
      GossipTag.find_by(id: params[:id]).destroy
    end

    Comment.all.each { |c| 
    if c.gossip_id == params[:id]
       c.destroy
      end
    }

    @gossip.destroy
    flash[:success] = "Le potin a été détruit !"
    redirect_to '/'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Salut à toi, #{@user.first_name} !"
      redirect_to root_path
    else
      flash[:alert] = "Email ou mot de passe invalide."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
    @colors = ["blue", "green", "brown", "purple", "orange"]
    @users = User.all
    @titles = Gossip.all
  end
  
  def team
  end

  def contact
  end

  def welcome
    @first_name = params[:first_name]
  end

  def show
    @index = Gossip.find(params[:id])
    @user = User.find(@index.user_id)
  end

  def user
    @user = User.find(params[:index_user])
    @ville = City.find(@user.city_id)
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def team
  end

  def contact
  end

  def welcome
    @first_name = params[:first_name]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], description: params[:description], 
                    age: params[:age], email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation],
                    city_id: City.all.sample.id)
    if @user.save
      @user.authenticate(params[:password])
      flash[:success] = "Compte crée avec succès ! \n Salut à toi, #{@user.first_name} !"
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages[0]
      Rails.logger.info(@user.errors.inspect)
      render 'new'
    end

  end

  def show
    @user = User.find(params['id'])
    @city = City.find(@user.city_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  
end

app/helpers/gossips_helper.rb
module GossipsHelper

  def already_exists?(gossip)
    return Like.where(user_id: current_user.id, gossip_id: gossip.id).length > 0
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return User.find_by(id: session[:user_id])
  end

  def log_in(user)
    return session[:user_id] = user.id
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/7bec0c7944.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </head>

  <body>

  <body class="bk_user">
    <nav class="navbar navbar-expand-sm navbar navbar-dark bg-primary" style="background-color: #e3f2fd">
      <%= link_to "GOSSIP Project", root_path, :class=>"navbar-brand", style:"margin-left: 10px"%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, :class=>"nav-link text-white" %>
          </li>
          <li class="nav-item active">
            <%= link_to "L'équipe", team_path, :class=>"nav-link text-white" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Contact", contact_path, :class=>"nav-link text-white" %>
          </li>
        <%if current_user%>
          <li class="nav-item active">
            <%= link_to "Créer un potin", new_gossip_path, :class=>"nav-link text-white" %>
          </li>
        <%end%>
        </ul>
        </div>

      <%if current_user%>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= button_to "Se déconnecter", session_path(current_user.id), :class=>"btn btn-primary", method: :delete %>
            </li>
          </ul>
        </div>
      <%else%>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "S'inscrire", new_user_path, :class=>"nav-link text-white" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Se connecter", new_session_path, :class=>"nav-link text-white" %>
            </li>
          </ul>
        </div>
      <%end%>

    </nav>

    <center>
      <% if flash[:success].present? %>
        <div class="alert alert-success custom_alert" role="alert">
          <%= flash[:success] %>
        </div>

        <%elsif flash[:alert].present?%>
        <div class="alert alert-danger custom_alert" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
      </center>

    <%= yield %>
  </body>
</html>